---
- name: Install system packages
  apt:
    pkg={{ item }}
    state=installed
    update_cache=true
  with_items: systemPackages

- name: Set locale module
  locale_gen:
    name=en_US.UTF-8
    state=present

- name: Set .bash_profile
  template:
    src=.bash_profile
    dest=/home/vagrant
    owner=vagrant
    group=vagrant
    mode=0644