---
#vhost_servername: "example.websoft.vagrant" -> needs to be set in group_vars
#vhost_sourceDir : "/message-service" -> needs to be set in group_vars
vhost_serveradmin: "support@websoft.ch"
vhost_relDestDir : "public"